drop table if exists city CASCADE;
create table city
(
    city_id     bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (city_id)
);

insert into city
values (null,'Не забудьте посетить Красную Площадь. Ну а в ЦУМ можно и не заходить)))', 'Москва'),
       (null,'Heloo', 'Минск')

