drop table if exists city CASCADE;
create table city
(
    city_id     bigint generated by default as identity,
    create_time varchar(255),
    description varchar(255),
    name        varchar(255),
    primary key (city_id)
);

insert into city
values (null, null, 'Heloo ', 'MINSK')

